name: firebase_image
description: A cached Flutter ImageProvider for Firebase Cloud Storage image objects.
version: 1.1.2
homepage: https://github.com/ash80/firebase_image

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
